// Generated by https://quicktype.io

class CastMoviesModel {
  int? id;
  String? name;
  String? originalName;
  double? popularity;
  String? profilePath;
  int? castId;
  String? character;
  String? creditId;
  int? order;
  String? job;

  CastMoviesModel({
    this.id,
    this.name,
    this.originalName,
    this.popularity,
    this.profilePath,
    this.castId,
    this.character,
    this.creditId,
    this.order,
    this.job,
  });

  factory CastMoviesModel.fromMap(Map<String, dynamic> map){
    return CastMoviesModel(
      id          : map['id'],
      name        : map['name'],
      originalName: map['original_name'],
      popularity  : map['popularity'],
      profilePath : map['profile_path'] ?? "",
      castId      : map['cast_id'] ?? "",
      character   : map['character']?? "",
      creditId    : map['credit_id'],
      order       : map['order']?? "",
      job         : map['job']?? ""
    );
  }
}

enum Department { ACTING, CREW, CAMERA, SOUND, PRODUCTION, ART, EDITING, COSTUME_MAKE_UP, DIRECTING, WRITING, VISUAL_EFFECTS }